package Study;

import java.io.IOException;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class First
 */
@WebServlet("/First")
public class First extends HttpServlet {


	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
	
	response.setContentType("text/plain");
	
	String poem_line1 = "twinkle twinkle little star" ;
	
	request.setAttribute("line1", poem_line1);//added name value pair to the request
	
	ServletContext context = super.getServletContext();//get containers reference and forward request to other servlet
	RequestDispatcher rd = context.getRequestDispatcher("/Second");//second servlet ko request send kiya 
	
	rd.forward(request, response);
	
	}

	
}
//this is forward chaining we call rd.forword();
//response is generated by the final servlet in the chain.....Third servlet here
//that response is send the browser by final servlet
//then request sent servlet to servlet.... that is chaining
//so in chaining same request object shared by all servlet is important