package Study;

import java.io.IOException;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class S1
 */
@WebServlet("/S1")
public class S1 extends HttpServlet {

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

		response.getWriter().append(" Ringa Ringa ");

		RequestDispatcher rd = super.getServletContext().getRequestDispatcher("/S2");

		rd.include(request, response);
	}




}
//this is include chaining we call rd.include();
//response is generated by the each servlet in the chain.....third to second .second to first
//that response is send the browser by first servlet 
//then request sent servlet to servlet.... that is chaining
//so in chaining same request object shared by all servlet is important